### ISSUE TITLE
Website resolution too high in browser

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#11]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26209690/cc25b9a6-3bed-11e7-8504-9c2d5517edac.png)

Expected behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26209722/e2c91f72-3bed-11e7-84bd-0c9627e77ba2.png)

**Comment by nickdotmulder** [comment]
Observed Behaviour:
<img width="1280" alt="screen shot 2017-05-18 at 5 21 07 pm" src="https://cloud.githubusercontent.com/assets/2698549/26209971/8e46ef8c-3bee-11e7-96bc-c0e1e688230c.png">

Expected Behaviour:
<img width="1278" alt="screen shot 2017-05-18 at 5 21 16 pm" src="https://cloud.githubusercontent.com/assets/2698549/26209970/8e34a3b8-3bee-11e7-968f-b07bef79fe6a.png">

The user needs to zoom out to 80% in order to see the complete header in the browser.

**Comment by bstarr322** [comment]
Fixed

**Comment by hypostef** [comment]
Appears that it is still not fixed.
